apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: nginx-jenkins
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort